"""Unit tests for the news-feature condition analysis (V2-03).

The conditional result rests on two pure computations — how a window's events are characterised,
and whether the gain is monotone in that characterisation. Both are pinned here so a refactor
cannot quietly change what the artifact means.
"""

from __future__ import annotations

import json
from pathlib import Path

from ml.forecasting.news_feature_conditions import CITYWIDE_BOROUGHS, event_composition

ALL_BOROUGHS = ["Manhattan", "Brooklyn", "Queens", "Bronx", "Staten Island"]


def _write(tmp_path: Path, rows: list[dict]) -> Path:
    p = tmp_path / "events.jsonl"
    p.write_text("\n".join(json.dumps(r) for r in rows) + "\n", encoding="utf-8")
    return p


def test_citywide_event_counts_as_citywide(tmp_path: Path) -> None:
    """A weather shock tagged to every borough is the case the mechanism is about."""
    path = _write(
        tmp_path,
        [
            {
                "d": "2026-02-03",
                "event_type": "WEATHER_SHOCK",
                "boroughs": ALL_BOROUGHS,
                "severity": 0.9,
            }
        ],
    )
    comp = event_composition(path)["2026-02"]
    assert comp["mean_boroughs_per_event"] == 5.0
    assert comp["citywide_share"] == 1.0


def test_localized_event_is_not_citywide(tmp_path: Path) -> None:
    path = _write(
        tmp_path,
        [
            {
                "d": "2026-06-14",
                "event_type": "PUBLIC_GATHERING",
                "boroughs": ["Manhattan"],
                "severity": 0.5,
            }
        ],
    )
    comp = event_composition(path)["2026-06"]
    assert comp["mean_boroughs_per_event"] == 1.0
    assert comp["citywide_share"] == 0.0


def test_citywide_threshold_is_four_boroughs(tmp_path: Path) -> None:
    """Three boroughs still leaves a borough with no event; four is the documented cut."""
    path = _write(
        tmp_path,
        [
            {"d": "2026-03-01", "boroughs": ALL_BOROUGHS[:3], "event_type": "X", "severity": 0.1},
            {"d": "2026-03-02", "boroughs": ALL_BOROUGHS[:4], "event_type": "X", "severity": 0.1},
        ],
    )
    comp = event_composition(path)["2026-03"]
    assert CITYWIDE_BOROUGHS == 4
    assert comp["citywide_share"] == 0.5  # only the 4-borough event counts


def test_months_are_separated_and_types_ranked(tmp_path: Path) -> None:
    path = _write(
        tmp_path,
        [
            {
                "d": "2026-02-01",
                "boroughs": ALL_BOROUGHS,
                "event_type": "WEATHER_SHOCK",
                "severity": 0.8,
            },
            {
                "d": "2026-02-09",
                "boroughs": ALL_BOROUGHS,
                "event_type": "WEATHER_SHOCK",
                "severity": 0.6,
            },
            {
                "d": "2026-06-02",
                "boroughs": ["Brooklyn"],
                "event_type": "PUBLIC_GATHERING",
                "severity": 0.4,
            },
        ],
    )
    comp = event_composition(path)
    assert set(comp) == {"2026-02", "2026-06"}
    assert comp["2026-02"]["n_events"] == 2
    assert comp["2026-02"]["dominant_types"][0].startswith("WEATHER_SHOCK")
    assert comp["2026-02"]["mean_severity"] == 0.7
    assert comp["2026-06"]["dominant_types"] == ["PUBLIC_GATHERINGx1"]


def test_committed_artifact_keeps_its_caveats() -> None:
    """The measured numbers must never travel without the limits that qualify them."""
    path = Path("reports/v2/llm_value/news_feature_conditions.json")
    if not path.exists():
        return  # artifact is regenerated by `make v2-news-conditions`; absence is not a failure
    payload = json.loads(path.read_text(encoding="utf-8"))
    assert payload["claim_status"] == "measured"
    assert payload["n_seeds"] >= 5, "a single-seed read of this comparison is not trustworthy"
    assert len(payload["limitations"]) >= 3
    assert payload["finding"]["mechanism"]
    assert payload["finding"]["training_size_rejected"]
    # Every window carries the coverage count that decides whether its verdict is readable.
    for w in payload["windows"]:
        assert "news_active_rows" in w
        assert "per_seed_std" in w
